import { CTA_FID } from "../../src/cta-teacher-homepage";

export type SyncRow = {
  teacherId: number;
  name: string;
  department: string | null;
  match: "none" | "unique" | "ambiguous";
  homepageUrl: string | null;
  ctaUid: number | null;
  avatarSha256: string | null;
  skippedDefaultAvatar: boolean;
  avatarBytes: number | null;
  contentType: string | null;
};

export function sqlString(value: string): string {
  return `'${value.replaceAll("'", "''")}'`;
}

export function homepageSql(rows: SyncRow[]): string {
  const statements = [
    "-- One-shot CTA homepage bind. Skip locked rows. Generated by pnpm cta-sync.",
    "BEGIN;",
  ];
  for (const row of rows) {
    if (row.match === "unique" && row.homepageUrl && row.ctaUid != null) {
      const avatarShaClause = row.avatarSha256
        ? `,avatar_sha256=${sqlString(row.avatarSha256)}`
        : "";
      statements.push(
        `UPDATE teachers SET cta_fid=${CTA_FID},cta_uid=${row.ctaUid},homepage_url=${sqlString(row.homepageUrl)},homepage_match='unique'${avatarShaClause},cta_synced_at=datetime('now') WHERE id=${row.teacherId} AND IFNULL(homepage_locked,0)=0;`,
      );
    } else {
      statements.push(
        `UPDATE teachers SET homepage_match=${sqlString(row.match)},cta_synced_at=datetime('now') WHERE id=${row.teacherId} AND IFNULL(homepage_locked,0)=0 AND IFNULL(homepage_match,'none') NOT IN ('unique','manual');`,
      );
    }
  }
  statements.push("COMMIT;", "");
  return statements.join("\n");
}
