import { CollectorEngine, DirectoryUnavailableError, buildFormBody, buildPageRequest, createCollectorState, type CollectorQuery, type CollectorState, type PageResponse } from "./collector-core";

declare global {
  interface Window { showDirectoryPicker?: (options?: { mode?: "read" | "readwrite"; id?: string }) => Promise<FileSystemDirectoryHandle>; }
  interface FileSystemHandle { queryPermission?: (descriptor?: { mode?: "read" | "readwrite" }) => Promise<PermissionState>; requestPermission?: (descriptor?: { mode?: "read" | "readwrite" }) => Promise<PermissionState>; }
}

const DB_NAME = "jufexk-catalog-collector-v1";
const STORE = "checkpoint";
const QUERY_FILTERS = { department:"",major:"",campus:"",category:"",courseName:"",teacherName:"",homeUnit:"" };
let state: CollectorState | undefined;
let directory: FileSystemDirectoryHandle | undefined;
let engine: CollectorEngine | undefined;
let frozenDictionary: SourceDictionary | undefined;

interface SourceOption { id:string; label:string }
interface SourceDictionary { schemaVersion:"catalog-capture-package/v1"; semesters:SourceOption[]; educationLevels:SourceOption[]; grades:SourceOption[]; homeUnits:SourceOption[]; majors:SourceOption[]; capturedAt:string; sha256:string }

function openDatabase() {
  return new Promise<IDBDatabase>((resolve,reject)=>{
    const request=indexedDB.open(DB_NAME,1);
    request.onupgradeneeded=()=>request.result.createObjectStore(STORE);
    request.onsuccess=()=>resolve(request.result); request.onerror=()=>reject(request.error);
  });
}

async function dbGet<T>(key:string):Promise<T|undefined>{const db=await openDatabase();return new Promise((resolve,reject)=>{const tx=db.transaction(STORE);const request=tx.objectStore(STORE).get(key);request.onsuccess=()=>resolve(request.result);request.onerror=()=>reject(request.error);});}
async function dbPut(key:string,value:unknown){const db=await openDatabase();await new Promise<void>((resolve,reject)=>{const tx=db.transaction(STORE,"readwrite");tx.objectStore(STORE).put(value,key);tx.oncomplete=()=>resolve();tx.onerror=()=>reject(tx.error);});}

function compareText(left:string,right:string){return left<right?-1:left>right?1:0;}
function stableJson(value:unknown):string{if(Array.isArray(value))return`[${value.map(stableJson).join(",")}]`;if(value&&typeof value==="object")return`{${Object.entries(value as Record<string,unknown>).sort(([a],[b])=>compareText(a,b)).map(([key,item])=>`${JSON.stringify(key)}:${stableJson(item)}`).join(",")}}`;return JSON.stringify(value);}
async function sha256(bytes:Uint8Array|string){const value=Uint8Array.from(typeof bytes==="string"?new TextEncoder().encode(bytes):bytes);return Array.from(new Uint8Array(await crypto.subtle.digest("SHA-256",value.buffer as ArrayBuffer))).map(byte=>byte.toString(16).padStart(2,"0")).join("");}

function options(id:string):SourceOption[]{const select=document.querySelector(`#${id}`) as HTMLSelectElement|null;if(!select)throw new Error(`missing source dictionary ${id}`);return Array.from(select.options).filter(option=>option.value).map(option=>({id:option.value,label:option.text.trim()}));}
async function readSourceDictionary():Promise<SourceDictionary>{
  const content={schemaVersion:"catalog-capture-package/v1" as const,semesters:options("xnxq"),educationLevels:options("sel_pycc"),grades:options("sel_nj"),homeUnits:options("sel_cddwdm"),majors:options("sel_zydm"),capturedAt:new Date().toISOString()};
  return {...content,sha256:await sha256(stableJson({...content,capturedAt:undefined}))};
}

function queryId(kind:string,semester:string,level:string,grade:string,index=0){return`${kind}-${semester.replace(/[^A-Za-z0-9]+/g,"-")}-${level}-${grade}${index?`-${index}`:""}`;}
function safeId(value:string){return value.replace(/[^A-Za-z0-9]+/g,"-").replace(/^-|-$/g,"")||"blank";}
function makeQuery(kind:CollectorQuery["kind"],semester:string,level:string,grade:string,extra:Record<string,string>={},index=0,identity=""):CollectorQuery{
  const [xn,xq]=semester.split(",");
  const id=`${queryId(kind,semester,level,grade,index)}${identity?`-${safeId(identity)}`:""}`;
  return {schemaVersion:"catalog-capture-package/v1",queryId:id,kind,dimensions:{semester,educationLevel:level,grade},filters:{...QUERY_FILTERS,major:extra.sel_zydm??"",homeUnit:extra.sel_cddwdm??""},requestParameters:{initQry:"0",xktype:"2",xn,xq,nj:grade,pycc:level,dwh:"",zydm:"",kclb1:"",kclb2:"",isbyk:"",items:"",xnxq:semester,sel_pycc:level,sel_nj:grade,sel_yxb:"",sel_zydm:"",kcmk:"",sel_schoolarea:"",sel_kclb1:"",sel_kclb2:"",sel_kc:"",sel_rkjs:"",sel_cddwdm:"",menucode_current:"S2020103",...extra},status:"pending",declaredRecordCount:0,capturedRecordCount:0,pageCount:0,nextPage:1,attempts:0};
}

type CaptureMode="single"|"pilot"|"full";
function buildPlan(dictionary:SourceDictionary,mode:CaptureMode){
  const current=(id:string)=>(document.querySelector(`#${id}`) as HTMLSelectElement|null)?.value||"";
  if(mode==="single")return[makeQuery("main",current("xnxq"),current("sel_pycc"),current("sel_nj"))];
  const result:CollectorQuery[]=[];
  const select=(values:SourceOption[],selected:string,limit:number)=>[...new Set([selected,...values.map(value=>value.id)].filter(Boolean))].slice(0,limit);
  const semesters=mode==="pilot"?select(dictionary.semesters,current("xnxq"),2):dictionary.semesters.map(value=>value.id);
  const levels=mode==="pilot"?select(dictionary.educationLevels,current("sel_pycc"),2):dictionary.educationLevels.map(value=>value.id);
  const grades=mode==="pilot"?select(dictionary.grades,current("sel_nj"),2):dictionary.grades.map(value=>value.id);
  for(const semester of semesters)for(const level of levels)for(const grade of grades)result.push(makeQuery("main",semester,level,grade));
  const base=result[Math.floor(Math.random()*result.length)]; const major=dictionary.majors[Math.floor(Math.random()*dictionary.majors.length)]?.id; const homeUnit=dictionary.homeUnits[Math.floor(Math.random()*dictionary.homeUnits.length)]?.id;
  if(base&&major)result.push(makeQuery("counterexample",base.dimensions.semester,base.dimensions.educationLevel,base.dimensions.grade,{sel_zydm:major},1,"major"));
  if(base&&homeUnit)result.push(makeQuery("counterexample",base.dimensions.semester,base.dimensions.educationLevel,base.dimensions.grade,{sel_cddwdm:homeUnit},2,"homeUnit"));
  return result;
}

type DictionaryName="semesters"|"educationLevels"|"grades"|"homeUnits"|"majors";
interface SourceChange{dictionary:DictionaryName;kind:"added"|"removed"|"renamed";id:string;before?:string;after?:string}
function diffDictionary(before:SourceDictionary,after:SourceDictionary){const changes:SourceChange[]=[];for(const name of ["semesters","educationLevels","grades","homeUnits","majors"] as DictionaryName[]){const oldValues=new Map(before[name].map(option=>[option.id,option.label]));const newValues=new Map(after[name].map(option=>[option.id,option.label]));for(const [id,label] of newValues){if(!oldValues.has(id))changes.push({dictionary:name,kind:"added",id,after:label});else if(oldValues.get(id)!==label)changes.push({dictionary:name,kind:"renamed",id,before:oldValues.get(id),after:label});}for(const [id,label] of oldValues)if(!newValues.has(id))changes.push({dictionary:name,kind:"removed",id,before:label});}return changes;}
function supplementalQueries(dictionary:SourceDictionary,changes:SourceChange[]){const queries:CollectorQuery[]=[];const changed=(name:DictionaryName)=>new Set(changes.filter(change=>change.dictionary===name&&change.kind!=="removed").map(change=>change.id));const semesters=changed("semesters"),levels=changed("educationLevels"),grades=changed("grades");for(const semester of dictionary.semesters)for(const level of dictionary.educationLevels)for(const grade of dictionary.grades)if(semesters.has(semester.id)||levels.has(level.id)||grades.has(grade.id))queries.push(makeQuery("supplemental",semester.id,level.id,grade.id,{},0,"dimensions"));for(const homeUnit of changed("homeUnits"))for(const semester of dictionary.semesters)for(const level of dictionary.educationLevels)for(const grade of dictionary.grades)queries.push(makeQuery("supplemental",semester.id,level.id,grade.id,{sel_cddwdm:homeUnit},0,`homeUnit-${homeUnit}`));for(const major of changed("majors"))for(const semester of dictionary.semesters)for(const level of dictionary.educationLevels)for(const grade of dictionary.grades)queries.push(makeQuery("supplemental",semester.id,level.id,grade.id,{sel_zydm:major},0,`major-${major}`));const unique=new Map(queries.map(query=>[query.queryId,query]));return [...unique.values()];}

async function ensureDirectoryPermission(){if(!directory)throw new DirectoryUnavailableError("capture directory is not selected");const permission=await directory.queryPermission?.({mode:"readwrite"});if(permission!=="granted"){const requested=await directory.requestPermission?.({mode:"readwrite"});if(requested!=="granted")throw new DirectoryUnavailableError("capture directory permission lost");}}
async function directoryFor(path:string[]){await ensureDirectoryPermission();let current=directory!;for(const part of path)current=await current.getDirectoryHandle(part,{create:true});return current;}
async function writePath(path:string,bytes:Uint8Array|string){const parts=path.split("/");const filename=parts.pop()!;const dir=await directoryFor(parts);const file=await dir.getFileHandle(filename,{create:true});const writer=await file.createWritable();await writer.write(typeof bytes==="string"?bytes:Uint8Array.from(bytes).buffer as ArrayBuffer);await writer.close();}
async function resetQuerySnapshots(queryId:string){const snapshots=await directoryFor(["snapshots"]);try{await snapshots.removeEntry(queryId,{recursive:true});}catch(error){if(!(error instanceof DOMException)||error.name!=="NotFoundError")throw error;}}

async function requestPage(query:CollectorQuery,page:number):Promise<PageResponse>{
  const {endpoint,requestParameters}=buildPageRequest(query,page,document.body.clientWidth);
  const response=await fetch(endpoint,{method:"POST",credentials:"same-origin",redirect:"follow",headers:{"Content-Type":"application/x-www-form-urlencoded"},body:buildFormBody(requestParameters)});
  const headers:Record<string,string>={};response.headers.forEach((value,key)=>headers[key.toLowerCase()]=value);
  return{status:response.status,url:response.url,headers,bytes:new Uint8Array(await response.arrayBuffer())};
}

async function hasDirectoryPermission(){return !!directory&&(await directory.queryPermission?.({mode:"readwrite"}))==="granted";}
async function writeLiveArtifacts(next:CollectorState){
  if(!await hasDirectoryPermission())return;
  const checkpoint=`${JSON.stringify({schemaVersion:"catalog-capture-package/v1",...next},null,2)}\n`;
  const partial=next.queries.map(query=>JSON.stringify(query)).join("\n")+"\n";
  await writePath("checkpoint.json",checkpoint);await writePath("queries.partial.jsonl",partial);
}
async function saveCheckpoint(next:CollectorState){state=next;await dbPut("state",next);if(directory)await dbPut("directory",directory);try{await writeLiveArtifacts(next);}catch(error){next.phase="directory_unavailable";next.log.push({at:new Date().toISOString(),event:"directory_unavailable",detail:error instanceof Error?error.message:String(error)});await dbPut("state",next);render();throw new DirectoryUnavailableError("capture directory is temporarily unavailable");}render();}
function createEngine(){return new CollectorEngine({request:requestPage,writeSnapshot:async(id,page,bytes)=>writePath(`snapshots/${id}/page-${String(page).padStart(4,"0")}.html`,bytes),resetQuerySnapshots,saveCheckpoint,sleep:ms=>new Promise(resolve=>setTimeout(resolve,ms)),now:()=>new Date().toISOString(),random:Math.random});}

async function planSourceSupplements(){if(!state||!frozenDictionary)return false;const current=await readSourceDictionary();if(current.sha256===frozenDictionary.sha256)return false;const changes=diffDictionary(frozenDictionary,current);state.sourceChangeRounds=(state.sourceChangeRounds??0)+1;const additions=supplementalQueries(current,changes).filter(query=>!state!.queries.some(existing=>existing.queryId===query.queryId));state.unresolvedSourceChanges=changes.filter(change=>change.kind==="removed").length;state.log.push({at:new Date().toISOString(),event:"source_changed",detail:JSON.stringify({round:state.sourceChangeRounds,changes,addedQueries:additions.length})});if(state.sourceChangeRounds>3){state.unresolvedSourceChanges=Math.max(1,state.unresolvedSourceChanges);state.log.push({at:new Date().toISOString(),event:"coverage_exception",detail:"source dictionary changed in more than three consecutive rounds"});return false;}state.queries.push(...additions);frozenDictionary=current;await dbPut("dictionary",current);await writePath("source-dictionary.json",`${JSON.stringify(current,null,2)}\n`);if(!additions.length)return false;state.phase="paused";await saveCheckpoint(state);return true;}
function sameDimensions(left:CollectorQuery,right:CollectorQuery){return left.dimensions.semester===right.dimensions.semester&&left.dimensions.educationLevel===right.dimensions.educationLevel&&left.dimensions.grade===right.dimensions.grade;}
function needsCounterexampleSupplement(){if(!state||!frozenDictionary)return false;const nonempty=state.queries.filter(query=>query.kind==="main"&&query.status==="complete"&&query.declaredRecordCount>0);if(!nonempty.length)return false;const counterexamples=state.queries.filter(query=>query.kind==="counterexample");const hasMajor=counterexamples.some(query=>!!query.filters.major&&nonempty.some(base=>sameDimensions(query,base)));const hasHomeUnit=counterexamples.some(query=>!!query.filters.homeUnit&&nonempty.some(base=>sameDimensions(query,base)));return (!hasMajor&&!!frozenDictionary.majors[0])||(!hasHomeUnit&&!!frozenDictionary.homeUnits[0]);}
async function planCounterexampleSupplements(){if(!state||!frozenDictionary||!needsCounterexampleSupplement())return false;const nonempty=state.queries.filter(query=>query.kind==="main"&&query.status==="complete"&&query.declaredRecordCount>0);const base=nonempty[0];const existing=state.queries.filter(query=>query.kind==="counterexample");const hasMajor=existing.some(query=>!!query.filters.major&&nonempty.some(candidate=>sameDimensions(query,candidate)));const hasHomeUnit=existing.some(query=>!!query.filters.homeUnit&&nonempty.some(candidate=>sameDimensions(query,candidate)));const additions:CollectorQuery[]=[];if(!hasMajor&&frozenDictionary.majors[0])additions.push(makeQuery("counterexample",base.dimensions.semester,base.dimensions.educationLevel,base.dimensions.grade,{sel_zydm:frozenDictionary.majors[0].id},3,"nonempty-major"));if(!hasHomeUnit&&frozenDictionary.homeUnits[0])additions.push(makeQuery("counterexample",base.dimensions.semester,base.dimensions.educationLevel,base.dimensions.grade,{sel_cddwdm:frozenDictionary.homeUnits[0].id},4,"nonempty-homeUnit"));const unique=additions.filter(query=>!state!.queries.some(existingQuery=>existingQuery.queryId===query.queryId));if(!unique.length)return false;state.queries.push(...unique);state.phase="paused";state.log.push({at:new Date().toISOString(),event:"counterexample_supplemented",detail:`${unique.length} queries based on ${base.queryId}`});await saveCheckpoint(state);return true;}
async function runToTerminal(){if(!state)return;while(true){engine=createEngine();engine.resume();await engine.run(state);if(state.phase!=="complete")break;if(await planCounterexampleSupplements())continue;if(!await planSourceSupplements()){await exportPackage();break;}}render();}

async function start(mode:CaptureMode){
  if(!window.showDirectoryPicker)throw new Error("File System Access API unavailable; use Chrome/Edge");
  if(state&&!window.confirm(`现有批次 ${state.batchId} 将保留在原目录。确认开始新的 ${mode} 批次？`))return;
  directory=await window.showDirectoryPicker({mode:"readwrite",id:"jufexk-catalog-capture"});
  frozenDictionary=await readSourceDictionary();
  state=createCollectorState(`${mode}-${new Date().toISOString().replace(/[:.]/g,"-")}`,buildPlan(frozenDictionary,mode));
  await dbPut("dictionary",frozenDictionary);await writePath("source-dictionary.json",`${JSON.stringify(frozenDictionary,null,2)}\n`);
  await runToTerminal();
}

async function resume(){state=state??await dbGet<CollectorState>("state");directory=directory??await dbGet<FileSystemDirectoryHandle>("directory");frozenDictionary=frozenDictionary??await dbGet<SourceDictionary>("dictionary");if(!state)throw new Error("no checkpoint");await ensureDirectoryPermission();await runToTerminal();}
async function retryExceptions(){if(!state)throw new Error("no checkpoint");const exceptions=state.queries.filter(query=>query.status==="exception");if(!exceptions.length)throw new Error("no exception queries");for(const query of exceptions){await resetQuerySnapshots(query.queryId);query.status="pending";query.nextPage=1;query.pageCount=0;query.declaredRecordCount=0;query.capturedRecordCount=0;query.lastError=undefined;}state.phase="paused";state.log.push({at:new Date().toISOString(),event:"exception_retry_started",detail:`${exceptions.length} queries`});await saveCheckpoint(state);await resume();}

function counts(){const statuses:Record<string,number>={};for(const query of state?.queries??[])statuses[query.status]=(statuses[query.status]??0)+1;return statuses;}
async function exportPackage(){if(!state||!frozenDictionary)throw new Error("no capture state");await ensureDirectoryPermission();const current=await readSourceDictionary();const sourceChanged=current.sha256!==frozenDictionary.sha256||(state.unresolvedSourceChanges??0)>0;state.log.push({at:new Date().toISOString(),event:"export_complete",detail:sourceChanged?"source_changed":"validated"});const queries=state.queries.map(({nextPage,attempts,lastError,...query})=>query);const queryText=queries.map(query=>JSON.stringify(query)).join("\n")+"\n";await writePath("queries.jsonl",queryText);
  const files:Array<{path:string;bytes:number;records:number;sha256:string}>=[];const add=async(path:string,bytes:Uint8Array|string,records:number)=>{const data=typeof bytes==="string"?new TextEncoder().encode(bytes):bytes;files.push({path,bytes:data.byteLength,records,sha256:await sha256(data)});};await add("queries.jsonl",queryText,queries.length);const dictionaryText=`${JSON.stringify(frozenDictionary,null,2)}\n`;await add("source-dictionary.json",dictionaryText,1);const logText=state.log.map(item=>JSON.stringify({schemaVersion:"catalog-capture-package/v1",...item})).join("\n")+"\n";await writePath("run-log.jsonl",logText);await add("run-log.jsonl",logText,state.log.length);const coverage={schemaVersion:"catalog-capture-package/v1",batchId:state.batchId,sourceChanged,sourceChangeRounds:state.sourceChangeRounds??0,unresolvedSourceChanges:state.unresolvedSourceChanges??0,queryCount:state.queries.length,statuses:counts(),exceptions:state.queries.filter(query=>query.status==="exception").map(query=>({queryId:query.queryId,page:query.nextPage,attempts:query.attempts,error:query.lastError}))};const coverageText=`${JSON.stringify(coverage,null,2)}\n`;await writePath("coverage.json",coverageText);await add("coverage.json",coverageText,1);const checkpointText=`${JSON.stringify({schemaVersion:"catalog-capture-package/v1",...state},null,2)}\n`;const partialText=state.queries.map(query=>JSON.stringify(query)).join("\n")+"\n";await writePath("checkpoint.json",checkpointText);await writePath("queries.partial.jsonl",partialText);await add("checkpoint.json",checkpointText,1);await add("queries.partial.jsonl",partialText,state.queries.length);
  for(const query of state.queries)for(let page=1;page<=query.pageCount&&page<query.nextPage;page++){const path=`snapshots/${query.queryId}/page-${String(page).padStart(4,"0")}.html`;const parts=path.split("/");const name=parts.pop()!;const dir=await directoryFor(parts);const handle=await dir.getFileHandle(name);const file=await handle.getFile();const buffer=await file.arrayBuffer();const bytes=new Uint8Array(buffer);await add(path,bytes,1);}
  files.sort((a,b)=>compareText(a.path,b.path));const manifestContent={schemaVersion:"catalog-capture-package/v1",batchId:state.batchId,status:sourceChanged?"source_changed":Object.keys(counts()).includes("exception")?"complete_with_exceptions":"complete",sourceDictionarySha256:frozenDictionary.sha256,counts:{queries:queries.length,pages:files.filter(file=>file.path.startsWith("snapshots/")).length,records:queries.reduce((sum,query)=>sum+(query.capturedRecordCount??(query.status==="complete"?query.declaredRecordCount:0)),0),bytes:files.reduce((sum,file)=>sum+file.bytes,0),statuses:counts()},files};const manifest={...manifestContent,manifestContentSha256:await sha256(stableJson(manifestContent))};await writePath("manifest.json",`${JSON.stringify(manifest,null,2)}\n`);await dbPut("state",state);if(directory)await dbPut("directory",directory);render();}

const phaseLabels:Record<CollectorState["phase"],string>={idle:"待开始",running:"采集中",paused:"已暂停",session_expired:"等待重新登录",directory_unavailable:"等待目录授权",circuit_open:"已安全熔断",stopped:"已停止",complete:"采集完成"};
function render(){const root=document.querySelector("#jufexk-catalog-panel") as HTMLElement|null;if(!root)return;const queries=state?.queries??[];const completed=queries.filter(query=>query.status==="complete").length;const exceptions=queries.filter(query=>query.status==="exception").length;const current=queries.find(query=>query.status!=="complete"&&query.status!=="exception");const percent=queries.length?Math.round((completed+exceptions)/queries.length*100):0;(root.querySelector("[data-phase]") as HTMLElement).textContent=state?phaseLabels[state.phase]:"待开始";(root.querySelector("[data-progress]") as HTMLElement).textContent=state?`${completed+exceptions} / ${queries.length} 查询 · ${percent}%`:"尚未创建计划";(root.querySelector("[data-current]") as HTMLElement).textContent=current?`${current.dimensions.semester} · ${current.dimensions.educationLevel} · ${current.dimensions.grade} · 第 ${current.nextPage}${current.pageCount?`/${current.pageCount}`:""} 页`:state?.phase==="complete"?"全部查询已到终态":"-";(root.querySelector("[data-bar]") as HTMLElement).style.width=`${percent}%`;(root.querySelector("[data-exceptions]") as HTMLElement).textContent=exceptions?`${exceptions} 个例外待定向补跑`:"无例外";const events=(state?.log??[]).slice(-6).reverse();(root.querySelector("[data-log]") as HTMLElement).innerHTML=events.map(item=>`<li><time>${item.at.slice(11,19)}</time><span>${item.event}${item.queryId?` · ${item.queryId}`:""}${item.page?` · p${item.page}`:""}</span></li>`).join("")||"<li>暂无事件</li>";const running=state?.phase==="running";(root.querySelector('[data-action="start"]') as HTMLButtonElement).disabled=!!state&&running;(root.querySelector('[data-action="pause"]') as HTMLButtonElement).disabled=!running;(root.querySelector('[data-action="resume"]') as HTMLButtonElement).disabled=!state||running||state.phase==="complete";(root.querySelector('[data-action="retry"]') as HTMLButtonElement).disabled=!exceptions;}
function showError(error:unknown){const root=document.querySelector("#jufexk-catalog-panel") as HTMLElement|null;if(root)(root.querySelector("[data-error]") as HTMLElement).textContent=error instanceof Error?error.message:String(error);}

function mount(){if(location.pathname!=="/student/wsxk.kcbcx10319.html"||document.querySelector("#jufexk-catalog-panel")||!document.querySelector("#ActionForm"))return;const panel=document.createElement("section");panel.id="jufexk-catalog-panel";panel.innerHTML=`<style>#jufexk-catalog-panel{position:fixed;right:12px;top:12px;z-index:2147483647;width:min(390px,calc(100vw - 24px));max-height:calc(100vh - 24px);overflow:auto;box-sizing:border-box;background:#fff;border:1px solid #b42318;border-top:4px solid #b42318;border-radius:6px;padding:14px;font:14px/1.45 system-ui;color:#252525;box-shadow:0 8px 28px #0003}#jufexk-catalog-panel *{box-sizing:border-box}#jufexk-catalog-panel header{display:flex;justify-content:space-between;align-items:center;margin-bottom:10px}#jufexk-catalog-panel h2{font-size:17px;margin:0;letter-spacing:0}#jufexk-catalog-panel [data-phase]{font-weight:700;color:#b42318}#jufexk-catalog-panel .meta{display:grid;gap:4px;background:#f6f6f6;padding:10px;border-radius:4px}#jufexk-catalog-panel .track{height:8px;background:#ddd;margin:10px 0;border-radius:4px;overflow:hidden}#jufexk-catalog-panel [data-bar]{height:100%;background:#16794b;width:0;transition:width .2s}#jufexk-catalog-panel select{width:100%;padding:8px;border:1px solid #aaa;border-radius:4px;background:white}#jufexk-catalog-panel .commands{display:grid;grid-template-columns:repeat(3,1fr);gap:6px;margin:10px 0}#jufexk-catalog-panel button{min-height:36px;border:1px solid #aaa;border-radius:4px;background:#fff;font-weight:600;cursor:pointer}#jufexk-catalog-panel button[data-action="start"],#jufexk-catalog-panel button[data-action="resume"]{background:#b42318;color:#fff;border-color:#b42318}#jufexk-catalog-panel button:disabled{opacity:.45;cursor:default}#jufexk-catalog-panel details{border-top:1px solid #ddd;padding-top:8px}#jufexk-catalog-panel ul{list-style:none;margin:6px 0 0;padding:0;font-size:12px}#jufexk-catalog-panel li{display:flex;gap:8px;padding:3px 0}#jufexk-catalog-panel time{color:#666;flex:none}#jufexk-catalog-panel [data-error]{color:#b42318;font-weight:600;word-break:break-word;min-height:20px}</style><header><h2>选课志目录采集</h2><span data-phase>载入中</span></header><div class="meta"><strong data-progress>读取检查点...</strong><span data-current>-</span><span data-exceptions>无例外</span></div><div class="track"><div data-bar></div></div><label>运行范围<select data-mode><option value="single">单查询验收</option><option value="pilot" selected>真实 Pilot · 小矩阵</option><option value="full">全量 · 冻结矩阵</option></select></label><div class="commands"><button data-action="start">开始新批次</button><button data-action="pause">暂停</button><button data-action="resume">授权并继续</button><button data-action="retry">重跑例外</button><button data-action="stop">安全停止</button><button data-action="export">立即整理包</button></div><div data-error></div><details><summary>最近事件</summary><ul data-log></ul></details>`;document.body.appendChild(panel);
  panel.querySelectorAll("button[data-action]").forEach(button=>(button as HTMLButtonElement).type="button");
  panel.addEventListener("click",event=>{const button=(event.target as HTMLElement).closest("button[data-action]") as HTMLButtonElement|null;if(!button)return;event.preventDefault();const action=button.dataset.action;const run=async()=>{showError("");if(action==="start")await start((((panel.querySelector("[data-mode]") as unknown) as HTMLSelectElement).value as CaptureMode));else if(action==="pause"){engine?.pause();}else if(action==="resume")await resume();else if(action==="retry")await retryExceptions();else if(action==="stop")engine?.stop();else if(action==="export")await exportPackage();};void run().catch(showError);});
  void Promise.all([dbGet<CollectorState>("state"),dbGet<FileSystemDirectoryHandle>("directory"),dbGet<SourceDictionary>("dictionary")]).then(async([savedState,savedDirectory,savedDictionary])=>{state=savedState;directory=savedDirectory;frozenDictionary=savedDictionary;render();if((state?.phase==="running"||state?.phase==="complete"&&needsCounterexampleSupplement())&&await hasDirectoryPermission())void runToTerminal().catch(showError);}).catch(showError);
}

mount();
